// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ammonowgtxzohwbkajml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFtbW9ub3dndHh6b2h3Ymtham1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNzMxNjMsImV4cCI6MjA2NTk0OTE2M30.mJz2nj5hPjErudkxbM75CB9Dy4Aw2IGUr-LoEyzwcVc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);